import { NgModule } from "@angular/core";
import { MatIconRegistry } from "@angular/material/icon";
import { DomSanitizer } from "@angular/platform-browser";

@NgModule({})
export class IconModule {
  constructor(
    private _domSanitizer: DomSanitizer, //utilizar url segura. Nos asegura que la ruta no eseta infectadaa por ninfun código malicioso
    private _matIconRegistry: MatIconRegistry
  ) {
    this._matIconRegistry.addSvgIcon(
      'twitter',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/twitter.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'my-doc',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/my-docs.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'offer',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/offer.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'file',
      this._domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/file.svg')
    );
    this._matIconRegistry.addSvgIcon(
      'my-profile',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/my-profile.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'user',
      this._domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/user.svg')
    );
    this._matIconRegistry.addSvgIcon(
      'order',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/order.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'search',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/search.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'plus',
      this._domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/plus.svg')
    );
    this._matIconRegistry.addSvgIcon(
      'cancel',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/cancel.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'logout',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/logout.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'edit',
      this._domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/edit.svg')
    );
    this._matIconRegistry.addSvgIcon(
      'delete',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/delete.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'menu',
      this._domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/menu.svg')
    );
    this._matIconRegistry.addSvgIcon(
      'eraser',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/eraser.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'elder_sign',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/elder_sign.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'edit_solid',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/edit_solid.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'save_regular',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/save_regular.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'upload_solid',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/upload_solid.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'visibility',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/visibility.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'visibility_off',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/visibility_off.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'computer',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/computer.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'arrow-circle-right',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/arrow-circle-right.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'arrow-circle-left',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/menu/arrow-circle-left.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'logo',
      this._domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/logo.svg')
    );
    this._matIconRegistry.addSvgIcon(
      'sign_out',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/sign_out.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'caret_down',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/caret_down.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'notification',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/notification.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'info',
      this._domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/info.svg')
    );
    this._matIconRegistry.addSvgIcon(
      'eye',
      this._domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/eye.svg')
    );
    this._matIconRegistry.addSvgIcon(
      'download',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/download.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'search_solid',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/search_solid.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'print',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/print.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'author',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/author.svg'
      )
    );
    this._matIconRegistry.addSvgIcon(
      'password',
      this._domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/icons/password.svg'
      )
    );
  }
}